#!/bin/bash

export RBENV_VERSION=$(cat .ruby-version)
export RBENV_ROOT=$HOME/.rbenv

unset GEM_PATH
unset GEM_HOME

if [ ! -d $RBENV_ROOT ]; then
    echo "Installing rbenv."
    git clone git://github.com/sstephenson/rbenv.git $RBENV_ROOT
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.profile
    echo 'eval "$(rbenv init -)"' >> ~/.profile
    source ~/.profile
fi

RBENV=$(which rbenv)

if [ "" = $RBENV ]; then
  RBENV="${RBENV_ROOT}/bin/rbenv"
fi

if [ ! -f $RBENV ]; then
  echo "Cannot find rbenv in your path or under .rbenv.  Please check your rbenv installation."
  exit
fi

if [ ! -d $RBENV_ROOT/plugins/rbenv-update ]; then
    echo "Installing rbenv-update plugin."
    git clone https://github.com/rkh/rbenv-update.git $RBENV_ROOT/plugins/rbenv-update
fi

if [ ! -d $RBENV_ROOT/plugins/ruby-build ]; then
    echo "Installing ruby-build plugin."
    git clone https://github.com/sstephenson/ruby-build.git $RBENV_ROOT/plugins/ruby-build
fi

if [ ! -d $RBENV_ROOT/plugins/rbenv-gemset ]; then
    echo "Installing rbenv-gemset plugin."
    git clone https://github.com/jf/rbenv-gemset.git $RBENV_ROOT/plugins/rbenv-gemset
fi

if [ ! -d $RBENV_ROOT/plugins/rbenv-vars ]; then
    echo "Installing rbenv-vars plugin."
    git clone https://github.com/sstephenson/rbenv-vars.git $RBENV_ROOT/plugins/rbenv-vars
fi

if [ ! -d $RBENV_ROOT/versions/$RBENV_VERSION ]; then
    echo "Installing ruby ${RBENV_VERSION}."
    $RBENV update
    $RBENV install $RBENV_VERSION
    echo "done"
elif [[ ("true" = "${RBENV_UPDATE:-false}") || ($(uname -a) =~ Darwin) ]]; then
    echo "Updating rbenv..."
    $RBENV update
else
    echo "Environment up to date, ruby version: $RBENV_VERSION"
fi

if [[ -d "${RBENV_ROOT}/bin" && ! $(echo $PATH | grep -F ".rbenv/bin") ]]; then
  echo "Adding rbenv to PATH - you need to restart your shell"
  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $HOME/.bash_profile
fi

if ! (type rbenv > /dev/null 2>&1); then
  echo "Initializing rbenv in your .bash_profile - you need to restart your shell"
  echo 'eval "$(rbenv init -)"' >> $HOME/.bash_profile
fi

$RBENV exec gem install --no-ri --no-rdoc bundler
$RBENV exec bundle install
$RBENV rehash
